package op

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	InstanceRouter
	ProjectRouter
	ServerRouter
	CicdPublishRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
